// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type User struct {
	ID           int32
	DisplayName  string
	Username     string
	Email        string
	PasswordHash string
	Verified     bool
}
