// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.queries.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (display_name, username, email, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateUserParams struct {
	DisplayName  string
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.DisplayName,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec

DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many

SELECT id, display_name, username, email, verified
FROM users
`

type GetAllUsersRow struct {
	ID          int32
	DisplayName string
	Username    string
	Email       string
	Verified    bool
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Username,
			&i.Email,
			&i.Verified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, display_name, username, email, verified
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID          int32
	DisplayName string
	Username    string
	Email       string
	Verified    bool
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.Email,
		&i.Verified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, display_name, username, email, verified
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          int32
	DisplayName string
	Username    string
	Email       string
	Verified    bool
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.Email,
		&i.Verified,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one

SELECT id, display_name, username, email, verified
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID          int32
	DisplayName string
	Username    string
	Email       string
	Verified    bool
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.Email,
		&i.Verified,
	)
	return i, err
}

const updateUserById = `-- name: UpdateUserById :one

UPDATE users
SET display_name = $2, email = $3, password_hash = $4, verified = $5
WHERE id = $1
RETURNING id, display_name, username, email, verified
`

type UpdateUserByIdParams struct {
	ID           int32
	DisplayName  string
	Email        string
	PasswordHash string
	Verified     bool
}

type UpdateUserByIdRow struct {
	ID          int32
	DisplayName string
	Username    string
	Email       string
	Verified    bool
}

func (q *Queries) UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (UpdateUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserById,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.Verified,
	)
	var i UpdateUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.Email,
		&i.Verified,
	)
	return i, err
}
