name: ci (openyan.org)

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging

jobs:
  build-web-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.0.6"

      - name: Install dependencies
        working-directory: ./web/openyan
        run: bun install

      - name: Lint code
        working-directory: ./web/openyan
        run: bun run lint

      - name: Build project
        working-directory: ./web/openyan
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        run: bun run build
