name: ci (web)

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash
      - name: Add Bun to PATH
        run: echo 'export BUN_INSTALL="$HOME/.bun"' >> $GITHUB_ENV && echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $GITHUB_ENV

      - name: Change directory to web
        run: cd web

      - name: Install dependencies
        working-directory: ./web
        run: bun install

      - name: Lint code
        working-directory: ./web
        run: bun lint

      - name: Build project
        working-directory: ./web
        run: bun build
